on: push

jobs:
  dagens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec ruby scraper.rb
    - run: echo "GITHUB_DAGENS_DEAL=$(tail -n 1 dagens.txt)" >> $GITHUB_ENV
    - name: Commit dagens deal
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: "dagens: ${{ env.DAGENS_DEALS }}"
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git checkout main
        git add dagens.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "$COMMIT_MSG"; git push origin main)
