name: Dagens scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  dagens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec ruby dagens_scraper.rb
    - run: echo "DAGENS_DEAL=$(tail -n 1 _data/dagens.json | cut -f2- -d-)" >> $GITHUB_ENV
    - name: Commit dagens deal
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: "action:${{ env.DAGENS_DEAL }}"
      run: |
        git config user.email github-actions@github.com
        git config user.name github-actions
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git checkout main
        git add _data/
        git diff
        git commit -m "$COMMIT_MSG"
        git push origin main
