on:
  schedule:
    - cron: '0 6 * * 2'

jobs:
  ukas_merke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec ruby ukas_merke_scraper.rb
    - run: echo "UKAS_MERKE=$(tail -n 1 ukas_merke.txt | cut -f2- -d-)" >> $GITHUB_ENV
    - name: Commit ukas merke
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: "action:${{ env.UKAS_MERKE }}"
      run: |
        git config user.email github-actions@github.com
        git config user.name github-actions
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git checkout main
        git add ukas_merke.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "$COMMIT_MSG"; git push origin main)
